// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npcgtjrgxxrhvrptkzip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wY2d0anJneHhyaHZycHRremlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTY4OTMsImV4cCI6MjA2MzI5Mjg5M30.tdFcNjEc-Y2CyHPIaGFaGUo25SRFCN24vjagMG8xg4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});