// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_URL = 'https://brrhnniybfabtnuxybal.supabase.co';
/** Só fallback de dev; produção deve definir VITE_SUPABASE_PUBLISHABLE_KEY ou VITE_SUPABASE_ANON_KEY. */
const DEFAULT_PUBLISHABLE_KEY = '';

function normalizeSupabaseUrl(url: string): string {
  return url.replace(/\/+$/, '');
}

/** Extrai o project ref do host `*.supabase.co`. */
export function projectRefFromSupabaseUrl(url: string): string | null {
  const m = url.match(/https?:\/\/([a-z0-9_-]+)\.supabase\.co/i);
  return m?.[1] ?? null;
}

const configuredUrl =
  import.meta.env.VITE_SUPABASE_URL?.trim() || DEFAULT_SUPABASE_URL;

export const SUPABASE_URL = normalizeSupabaseUrl(configuredUrl);

export const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() ||
  import.meta.env.VITE_SUPABASE_ANON_KEY?.trim() ||
  DEFAULT_PUBLISHABLE_KEY;

const refFromEnv = import.meta.env.VITE_SUPABASE_PROJECT_ID?.trim();
const refFromUrl = projectRefFromSupabaseUrl(SUPABASE_URL);

export const CURRENT_PROJECT_REF =
  refFromEnv || refFromUrl || 'brrhnniybfabtnuxybal';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/** Em dev (Vite), auth HTTP passa pelo proxy — mesmo origin evita CORS falso quando há falha na edge. */
const DEV_SB_AUTH_PROXY_PREFIX = '/__sb_proxy';

function resolveRequestUrl(input: RequestInfo | URL): string {
  if (typeof input === 'string') return input;
  if (input instanceof URL) return input.href;
  return (input as Request).url;
}

/** Só redes `.../auth/v1/*`; PostgREST/realtime continuam direto ao host. */
async function devSupabaseFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  let backendHostname = '';
  try {
    backendHostname = new URL(SUPABASE_URL).hostname;
  } catch {
    /* ignore */
  }

  const urlStr = resolveRequestUrl(input);

  const useProxy =
    import.meta.env.DEV &&
    typeof window !== 'undefined' &&
    Boolean(backendHostname) &&
    urlStr.includes(backendHostname) &&
    urlStr.includes('/auth/v1/');

  if (!useProxy) {
    return fetch(input, init as RequestInit);
  }

  const u = new URL(urlStr);
  const proxied = `${DEV_SB_AUTH_PROXY_PREFIX}${u.pathname}${u.search}`;

  if (typeof input === 'string') {
    return fetch(proxied, init);
  }
  if (input instanceof URL) {
    return fetch(proxied, init);
  }

  const req = input as Request;
  const method = req.method;
  let body: BodyInit | null | undefined;
  if (method === 'GET' || method === 'HEAD') {
    body = undefined;
  } else {
    body = await req.clone().arrayBuffer();
  }
  return fetch(proxied, {
    method,
    headers: req.headers,
    body,
  });
}

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    ...(import.meta.env.DEV && typeof window !== 'undefined'
      ? { global: { fetch: devSupabaseFetch } }
      : {}),
  },
);

/**
 * Check if the current token is valid, attempt refresh if needed.
 * Returns true if the session is valid after check.
 */
export async function checkToken(): Promise<boolean> {
  try {
    const { data: { session }, error } = await supabase.auth.getSession();
    if (error || !session) {
      // Try refreshing
      const { data: refreshData, error: refreshError } = await supabase.auth.refreshSession();
      if (refreshError || !refreshData.session) {
        return false;
      }
      return true;
    }
    // Check if token is about to expire (within 60 seconds)
    const expiresAt = session.expires_at;
    if (expiresAt && expiresAt * 1000 - Date.now() < 60000) {
      const { error: refreshError } = await supabase.auth.refreshSession();
      return !refreshError;
    }
    return true;
  } catch {
    return false;
  }
}

/**
 * Check if there was a recent successful authentication (within last 5 seconds).
 * Used to avoid unnecessary re-auth checks right after login.
 */
let lastAuthTimestamp = 0;
export function wasRecentlyAuthenticated(): boolean {
  return Date.now() - lastAuthTimestamp < 5000;
}

// Update timestamp on auth state changes
supabase.auth.onAuthStateChange((event) => {
  if (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') {
    lastAuthTimestamp = Date.now();
  }
});

/**
 * Cleanup all realtime channels
 */
export function cleanupAllChannels(): void {
  supabase.removeAllChannels();
}
