// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://adzaqkduxnpckbcuqpmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkemFxa2R1eG5wY2tiY3VxcG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5ODgyMDksImV4cCI6MjA4MTU2NDIwOX0.WO9-vzv_Vuh86TQWgNWuQ45cXa-L4GoGQfpSbvQiVMc";
export const CURRENT_PROJECT_REF = "adzaqkduxnpckbcuqpmg";

// Limpar apenas sessões de OUTROS projetos do Supabase ao inicializar
// NÃO limpar a sessão do projeto atual para permitir persistência
if (typeof window !== 'undefined') {
  // Limpar apenas chaves de OUTROS projetos, não a do projeto atual
  const currentStorageKey = `sb-${CURRENT_PROJECT_REF}-auth-token`;
  const keysToRemove: string[] = [];
  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (key) {
      // Remover apenas chaves do Supabase que NÃO são do projeto atual
      if ((key.startsWith('sb-') || key.includes('supabase')) && key !== currentStorageKey) {
        keysToRemove.push(key);
      }
    }
  }
  
  keysToRemove.forEach(key => localStorage.removeItem(key));
  
  // Também limpar sessionStorage de outros projetos
  const sessionKeysToRemove: string[] = [];
  for (let i = 0; i < sessionStorage.length; i++) {
    const key = sessionStorage.key(i);
    if (key && (key.startsWith('sb-') || key.includes('supabase')) && key !== currentStorageKey) {
      sessionKeysToRemove.push(key);
    }
  }
  sessionKeysToRemove.forEach(key => sessionStorage.removeItem(key));
  
  console.log('✅ Cliente Supabase inicializado para projeto: adzaqkduxnpckbcuqpmg');
  console.log('✅ URL:', SUPABASE_URL);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: `sb-${CURRENT_PROJECT_REF}-auth-token`, // Forçar chave específica do projeto
    detectSessionInUrl: false, // Não detectar sessão na URL
    flowType: 'pkce', // Usar PKCE flow para segurança
  },
  global: {
    headers: {
      'apikey': SUPABASE_PUBLISHABLE_KEY,
    },
    fetch: (url, options = {}) => {
      // Usar fetch nativo com timeout no nível HTTP
      const controller = new AbortController();
      const timeoutId = setTimeout(() => {
        controller.abort();
      }, 30000);

      // Combinar signals se ambos existirem
      const combinedSignal = options.signal || controller.signal;
      if (options.signal && controller.signal) {
        options.signal.addEventListener('abort', () => {
          controller.abort();
        });
      }

      return fetch(url, {
        ...options,
        signal: combinedSignal,
      })
        .then((response) => {
          clearTimeout(timeoutId);
          return response;
        })
        .catch((error) => {
          clearTimeout(timeoutId);
          throw error;
        });
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Monitorar eventos de refresh de token
if (typeof window !== 'undefined') {
  // Listener para eventos de autenticação
  supabase.auth.onAuthStateChange((event, session) => {
    if (event === 'TOKEN_REFRESHED') {
      console.log('✅ Token refreshed successfully');
    } else if (event === 'SIGNED_OUT') {
      console.log('🔒 User signed out');
    }
  });

  // Função para verificar e fazer refresh do token proativamente
  const checkAndRefreshToken = async () => {
    try {
      const { data: { session }, error } = await supabase.auth.getSession();

      if (error || !session) {
        return;
      }

      const now = Math.floor(Date.now() / 1000);
      const tokenExpiry = session.expires_at;
      const timeUntilExpiry = tokenExpiry ? tokenExpiry - now : null;

      // Se o token está próximo de expirar (menos de 10 minutos), tentar refresh
      // Aumentado de 5 para 10 minutos para ser mais proativo
      if (timeUntilExpiry !== null && timeUntilExpiry > 0 && timeUntilExpiry < 600) {
        console.log(`⏰ Token expira em ${Math.round(timeUntilExpiry / 60)} minutos. Fazendo refresh...`);
        const { error: refreshError } = await supabase.auth.refreshSession();
        if (refreshError) {
          console.error('❌ Erro ao fazer refresh do token:', refreshError.message);
        }
      }
    } catch (err: any) {
      console.error('❌ Erro ao verificar token:', err.message);
    }
  };

  // Verificar token a cada 30 segundos (mais frequente para evitar expiração)
  setInterval(checkAndRefreshToken, 30000);

  // Verificar imediatamente ao carregar
  setTimeout(checkAndRefreshToken, 1000);

  // Também verificar quando a janela recebe foco (usuário volta para a aba)
  window.addEventListener('focus', () => {
    checkAndRefreshToken();
  });

  // Verificar quando a conexão é restabelecida
  window.addEventListener('online', () => {
    console.log('🌐 Conexão restabelecida. Verificando token...');
    checkAndRefreshToken();
  });
}

// Exportar URL e Project Ref para uso em outros lugares
export const SUPABASE_PROJECT_URL = SUPABASE_URL;
export const SUPABASE_PROJECT_REF = CURRENT_PROJECT_REF;

// VALIDAÇÃO RIGOROSA: Garantir que estamos usando o projeto correto
if (CURRENT_PROJECT_REF !== 'adzaqkduxnpckbcuqpmg') {
  throw new Error(
    `❌ ERRO CRÍTICO: Project Ref incorreto! Esperado: adzaqkduxnpckbcuqpmg, Atual: ${CURRENT_PROJECT_REF}`
  );
}

if (SUPABASE_URL !== 'https://adzaqkduxnpckbcuqpmg.supabase.co') {
  throw new Error(
    `❌ ERRO CRÍTICO: URL do Supabase incorreta! Esperado: https://adzaqkduxnpckbcuqpmg.supabase.co, Atual: ${SUPABASE_URL}`
  );
}

// DEBUG: Verificar configuração ao inicializar
if (typeof window !== 'undefined') {
  console.log('✅ Supabase Client Configurado:');
  console.log('   URL:', SUPABASE_URL);
  console.log('   Project Ref:', CURRENT_PROJECT_REF);
  console.log('   Storage Key:', `sb-${CURRENT_PROJECT_REF}-auth-token`);
  
  // Verificar se há sessão armazenada
  const storedSession = localStorage.getItem(`sb-${CURRENT_PROJECT_REF}-auth-token`);
  if (storedSession) {
    console.log('⚠️ Sessão encontrada no localStorage. Verificando validade...');
    try {
      const sessionData = JSON.parse(storedSession);
      if (sessionData?.access_token) {
        // Decodificar JWT para verificar o projeto
        const payload = JSON.parse(atob(sessionData.access_token.split('.')[1]));
        console.log('   JWT Payload:', payload);
        console.log('   JWT Issuer:', payload.iss);
        if (payload.iss && !payload.iss.includes(CURRENT_PROJECT_REF)) {
          console.error('❌ ERRO: JWT token é de outro projeto!', payload.iss);
          console.error('   Limpando sessão inválida...');
          localStorage.removeItem(`sb-${CURRENT_PROJECT_REF}-auth-token`);
        }
      }
    } catch (e) {
      console.warn('   Não foi possível decodificar JWT:', e);
    }
  }
}